### ISSUE TITLE
Installation de flutter

### ISSUE THREAD

**Issue by Chevalier-du-web** [DJUIKOM/GREEN-TRACK#1]
* Telecharger flutter , android studio, viual studio code.

* vérifier l'les installations.

**Comment by DJUIKOM** [comment]
Installation reuissie

**Comment by DJUIKOM** [comment]
ok

**Comment by Chevalier-du-web** [comment]
instalation de git finie.

![image](https://github.com/DJUIKOM/GREEN-TRACK/assets/89807019/f966825f-042f-4a97-af9d-c00e8e1bd360)
